stages:
    ComputeRDF:
        cmd: 'python3 -c "from main import ComputeRDF; ComputeRDF.load(name=''ComputeRDF'').run_and_save()" '
        deps:
        - nodes/RunMD/outs.json
        desc: Calculate RDF whatever that means...
        outs:
        - nodes/ComputeRDF/outs.json
        params:
        - ComputeRDF
    GetAtoms:
        cmd: 'python3 -c "from main import GetAtoms; GetAtoms.load(name=''GetAtoms'').run_and_save()" '
        desc: Generate Atoms for Simulation
        outs:
        - nodes/GetAtoms/outs.json
        params:
        - GetAtoms
    RunMD:
        cmd: 'python3 -c "from main import RunMD; RunMD.load(name=''RunMD'').run_and_save()" '
        deps:
        - nodes/GetAtoms/outs.json
        desc: Run Simulation
        outs:
        - nodes/RunMD/outs.json
        params:
        - RunMD
